# Generated by Django 5.2 on 2025-09-17 09:31

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('usage_percent', models.FloatField(help_text='CPU usage percentage for this user')),
                ('cores', models.IntegerField(help_text='Number of CPU cores')),
                ('frequency_mhz', models.FloatField(blank=True, help_text='CPU frequency in MHz', null=True)),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_usage_records', to='core.node')),
            ],
            options={
                'verbose_name': 'CPU Usage Record',
                'verbose_name_plural': 'CPU Usage Records',
                'indexes': [models.Index(fields=['username'], name='cpu_monitor_usernam_9d9701_idx'), models.Index(fields=['usage_percent'], name='cpu_monitor_usage_p_3adc7c_idx')],
            },
        ),
    ]
