# Generated by Django 5.2 on 2025-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cpuusage',
            name='cpu_monitor_usernam_9d9701_idx',
        ),
        migrations.RemoveField(
            model_name='cpuusage',
            name='cores',
        ),
        migrations.RemoveField(
            model_name='cpuusage',
            name='username',
        ),
        migrations.AddField(
            model_name='cpuusage',
            name='cores_logical',
            field=models.IntegerField(default=0, help_text='Number of logical CPU cores'),
        ),
        migrations.AddField(
            model_name='cpuusage',
            name='cores_physical',
            field=models.IntegerField(default=0, help_text='Number of physical CPU cores'),
        ),
        migrations.AlterField(
            model_name='cpuusage',
            name='usage_percent',
            field=models.FloatField(help_text='Overall CPU usage percentage for the node'),
        ),
    ]
