# Generated by Django 5.2 on 2025-04-10 14:44

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('memory_total', models.BigIntegerField(help_text='Total memory in MB')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpus', to='core.node')),
            ],
            options={
                'verbose_name': 'GPU',
                'verbose_name_plural': 'GPUs',
                'unique_together': {('node', 'gpu_id')},
            },
        ),
        migrations.CreateModel(
            name='GPUUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('memory_used', models.BigIntegerField(help_text='Memory used in MB')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='gpu_monitor.gpu')),
            ],
            options={
                'verbose_name': 'GPU Usage Record',
                'verbose_name_plural': 'GPU Usage Records',
                'indexes': [models.Index(fields=['username'], name='gpu_monitor_usernam_d0795e_idx')],
            },
        ),
    ]
