# Generated by Django 5.2 on 2025-04-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpu_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpu',
            name='memory_total',
            field=models.FloatField(help_text='Total memory in MB'),
        ),
        migrations.AlterField(
            model_name='gpuusage',
            name='memory_used',
            field=models.FloatField(help_text='Memory used in MB'),
        ),
    ]
